version: '3.8'

services:
  redis:
    image: redis:6.2-alpine
    volumes:
      - ./data/redis:/usr/local/etc/redis
  elasticsearch:
    image: elasticsearch:7.13.2
    environment:
      - xpack.security.enabled=true
      - node.name=vibhuvi-node
      - discovery.type=single-node
      - cluster.name=vibhuvi-es-data-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1024m -Xmx1024m"
      - ELASTIC_PASSWORD=password
    ports:
      - 9200:9200
      - 9300:9300
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - './data/elastic:/usr/share/elasticsearch/data'
  postgres:
    image: postgres:alpine3.15
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=user
      - POSTGRES_DB=db
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
  mysql:
    image: mysql:8.0.27
    volumes:
      - ./data/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=db
      - MYSQL_USER=user 
      - MYSQL_PASSWORD=password
    ports:
      - 3306:3306
  db2:
    image: ibmcom/db2:11.5.7.0
    environment:
      - LICENSE=accept
      - DB2INST1_PASSWORD=password
      - DBNAME=db
    volumes:
      - ./data/db2::/database
  mssql:
    image: mcr.microsoft.com/mssql/server:2019-CU14-ubuntu-20.04
    environment:
      - "ACCEPT_EULA=Y" 
      - "SA_PASSWORD=password"
    ports:
      - 1433:1433 
  couchdb:
    image: couchdb:3.2.0
    volumes:
     - ./data/couchdb:/opt/couchdb/data
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=password
  rabbitmq:
    image: rabbitmq:3.8-alpine
  spring-config:
    image: hyness/spring-cloud-config-server:jre11
    ports:
      - 8888:8888
  hazelcast:
    image: hazelcast/hazelcast:5.1-SNAPSHOT-slim
    ports:
      - 5701:5701
    environment:
      - JAVA_OPTS="-Xms512M -Xmx1024M"
  mongo:
    image: mongo:5.0
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=example
    volumes:
      - ./data/mongo:/data/db
    ports:
      - 27017:27017
  nginx:
    image: nginx:1.21-alpine
  # tranquillity:
  #   image: freonius/tranquillity:v0.1.0
  #   build:
  #     context: .
  #     dockerfile: ./Dockerfile
  #     args:
  #       TQ_VERSION: v0.1.0