name: Python
on: [push]
jobs:
  Python:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Check docker and docker-compose
        run: docker info && docker-compose version
      - name: Pull necessary docker images (for testing)
        run: docker pull hyness/spring-cloud-config-server:latest
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Run linter, tests, and build
        run: bash ./setup.sh py -l -t -i -b -m shell utils exceptions settings
      - name: Upload coverage
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage/shell.xml,./coverage/utils.xml,./coverage/exceptions.xml,./coverage/settings.xml
      - name: Publish testpypi
        run: bash ./setup.sh py -p -m shell utils exceptions settings
        env:
          PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
          TESTPYPI_TOKEN: ${{ secrets.TESTPYPI_TOKEN }}
          
      # - name: Publish package to PyPI
      #   if: github.ref == 'refs/heads/master'
      #   uses: pypa/gh-action-pypi-publish@release/v1
      #   with:
      #     user: __token__
      #     password: ${{ secrets.PYPI_TOKEN }}
      #     packages_dir: ./dist
      

  build-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: freonius
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: freonius/tranquillity:latest
          file: ./Dockerfile