name: Python
on: [push]
jobs:
  Python:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Run linter, tests, and build
        run: bash ./setup.sh py -l -t -i -b -m shell utils exceptions settings
      - name: Upload coverage
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage/shell.xml,./coverage/utils.xml,./coverage/exceptions.xml,./coverage/settings.xml
      - name: Publish testpypi
        run: bash ./setup.sh py -p -m shell utils exceptions settings
        env:
          PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
          TESTPYPI_TOKEN: ${{ secrets.TESTPYPI_TOKEN }}
          
      # - name: Publish package to PyPI
      #   if: github.ref == 'refs/heads/master'
      #   uses: pypa/gh-action-pypi-publish@release/v1
      #   with:
      #     user: __token__
      #     password: ${{ secrets.PYPI_TOKEN }}
      #     packages_dir: ./dist
      