name: Run pytest
on: [push]
jobs:
  Run-Tests:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Install requirements
        run: sh ./scripts/sh/install_python_requirements.sh
      - name: Install modules
        run: sh ./scripts/sh/install_python_modules.sh
      - name: Run all tests
        run: sh ./scripts/sh/run_pytests.sh
      - name: Upload coverage
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage/shell.xml
      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: Freonius
          password: ${{ secrets.PYPI_TOKEN }}
          packages_dir: ./src/python/shell/
      