name: Run pytest
on: [push]
jobs:
  Run-Tests:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: cd ./src/python/shell && python -m pip install -r ./requirements.txt && python -m pip install -r ./requirements-dev.txt
      - name: Run tests
        run: sh ./pytest-tq.sh